management.endpoints.web.exposure.include:
  - auditevents
  - beans
  - conditions
  - configprops
  - env
  - health
  - heapdump
  - info
  - logfile
  - loggers
  - mappings
  - metrics
  - sessions
  - startup
  - threaddump

server:
  port: 1200

spring:
  application.name: java-experiments
  ai:
    ollama:
      chat:
        options:
          model: llama3
  webflux:
    base-path: /api

springdoc.show-actuator: true

